### ISSUE TITLE
Command to 'wake up' the v2 keypad so the lights come on

### ISSUE THREAD

**Issue by davidcoulson** [ImSorryButWho/HomeAssistantNotes#10]
Thanks for all this documentation - I was able to build a working integration between Alarmo and the Ring V2 keypad in Node-Red using this info. Really appreciate it.

Do you know of avcommand I can run that would 'wake up the keypad similar to if someone walks in front of it? Our old alarm system was lit all the time, so we would eyeball it before we open the back doors for the dog to go out. We've got the keypad permanently powered via the USB port, so it should not be running in a power saving mode.

**Comment by ImSorryButWho** [comment]
That's a great question.  I haven't noticed any way to do that, but there's
still a few indicators it claim to support that I haven't figured out what
they do.  I'll experiment a bit and get back to you.

**Comment by ImSorryButWho** [comment]
Looking at the [docs](https://support.ring.com/hc/en-us/articles/360042696611-Ring-Alarm-Keypad-2nd-gen-Z-Wave-Technical-Manual), I think you want configuration parameter 21.  Set it to 601, and the current mode will always be lit up.

**Comment by davidcoulson** [comment]
>  I think you want configuration parameter 21. Set it to 601, and the current mode will always be lit up.

Thanks! For some reason, it is actually parameter 22, but setting it to 601 works great.
