### ISSUE TITLE
Alarm ask to bypass sensors when door is opened

### ISSUE THREAD

**Issue by Gahrlaag** [ImSorryButWho/HomeAssistantNotes#13]
So I'm having issues with my ring keypad and Alarmo. Suddenly, when I arm away, and open the door to leave the premises, the keypad asks to bypass the sensors and goes into disarmed state.

**Comment by Gahrlaag** [comment]
I had accidentally set a door sensor as a tamper sensor. Changing to door did the trick.

**Comment by mcondren** [comment]
I do have mine set as type door, and am still having this issue. Set away, starts to count down, I open the door to leave and it says bypass and aborts. Any other ideas?

**Comment by ImSorryButWho** [comment]
@mcondren - That's an Alarmo problem, not a keypad problem.  If there's really a bug, they will be able to help.

That said, is "use exit delay" selected in the advanced settings for the sensor?

**Comment by mcondren** [comment]
Thanks, I will check that, and if so I will post over in the Alarmo repo.

**Comment by Dinth** [comment]
Hey @mcondren have you filled a bug report with Alarmo?

**Comment by mcondren** [comment]
@Dinth, no. I got mine working. My memory is unclear on how I got it working but it may have been the exit delay checkbox mentioned above.
