### ISSUE TITLE
Triggers from Armed Home/Stay State

### ISSUE THREAD

**Issue by KidA001** [ImSorryButWho/HomeAssistantNotes#24]
First off thank you for putting this together, it's saved me a bunch of time.

Right now when Alarmo is in a Armed Home/Stay state and a sensor is triggered, it sends the generic Alarm noise to the keypad. This is a little jarring as if I'm at home I would usually just want one of the [Notification Sounds](https://github.com/ImSorryButWho/HomeAssistantNotes/blob/main/RingKeypadV2.md#notification-sounds-use-property_key-9-to-specify-volume) triggered. Is there any way to change this? It looks like the blueprint doesn't differentiate when Alarmo goes to triggered from whichever state it's in.

Thanks!

**Comment by ImSorryButWho** [comment]
Feel free to fork the code and do whatever works for you.  But this seems like an extremely niche use case, and breaks the fundamental idea of reflecting the Alarmo state on the keypad.

Here Alarmo is working the way every commerical alarm I've ever used works: a triggered alarm sounds the siren, no matter what mode it was triggered from.  Most alarm systems do have a notification sound or announcement for an open sensor, when the system is disarmed.  That's not something Alarmo currently supports, but it's a simple automation to build yourself.  If you need help, I can throw together a blueprint.
