### ISSUE TITLE
Keypad spoken language

### ISSUE THREAD

**Issue by tardich** [ImSorryButWho/HomeAssistantNotes#26]
Nice work !!!   The keypad worked like a charm as soon as I implemented the blueprint !

One question, though, for which I can't find an answer. Is there any way to change the spoken language of the keypad? Right now, it's in English, and I'd like it to speak my native language, which is french.

**Comment by ImSorryButWho** [comment]
Yes.  Configuration parameter 18 controls the spoken language.  Set it to 2 for French.

For anyone finding this in the future, 0 is English and 5 is Spanish.  It's possible the European version has more options, but those are the languages in the North American version.

**Comment by tardich** [comment]
Thanks for the prompt answer. Unfortunately, I must be missing something. How do I get/set these Configuration parameters?

**Comment by ImSorryButWho** [comment]
On the Device page for the keypad, click the Configure button.  That will open up a page showing all the configuration parameters for the device, as defined in the [ZwaveJS database](https://devices.zwave-js.io/?jumpTo=0x0346:0x0101:0x0301:0.0).  Scroll down to the parameter you want to change (18, in this case), and change the value.

You can also use the `zwave_js.set_configuration_parameter` service, but that's overkill for this user case.

**Comment by tardich** [comment]
Thanks a lot for the help. Growing up !  :-)
