### ISSUE TITLE
Ring Keypad V2 issues after upgrade HA Core from 2024.6.4 to 2024.7.x

### ISSUE THREAD

**Issue by wardrp** [ImSorryButWho/HomeAssistantNotes#33]
Hello, Firstly, thank you for your great work it has helped me a lot and I have been using your blueprints for KeypadV2 for several months now.

I had issues with my Ring Keypad V2 when I upgraded my HomeAssistant Core to 2024.7.3. The first indication of something wrong was the Ring Keypad displayed the RED network icon indicating it had lost connection to HomeAssistant. Multiple restarts, reboots, cold reboots, etc. did not resolve the isssue. HomeAssistant would show the Keypad as if it was connected but seemed only some parts were working. Mean-while the RED network icon was still displaying on the Keypads. I have 2 of the V2 Keypads and both had the same issues.

I gave up on HA CORE 2024.7.x and restored my homeassistant back to HA CORE 2024.6.4 where everything was working. But even in the restored homeassistant the V2 Keypads still had the RED network icon. I ended up having to completely delete them from my configuration and reset them. Then add them back. After doing that they are now working again perfectly in HA CORE 2024.6.4. 

Now I am afraid to try updating HA CORE to 2024.7.x, but I don't see anyone else complaining about this issue. So maybe it was just a fluke or bad update or something that caused it? I don't know. I was wondering if you have heard of anyone having issues with the V2 Ring Keypads in HomeAssistant with the HA Core 2024.7.x update?

Thanks for your work and time.

**Comment by ImSorryButWho** [comment]
I've been running 2024.7.x for a few weeks, and haven't noticed any trouble.  

The Home Assistant core version isn't likely to cause comms issues with ZWave devices by itself, since those comms are all mediated by the ZWaveJS server.   Did you upgrade your ZWaveJS server to a version supported by 2024.7 before you upgraded HA?  See the [HA release notes](https://www.home-assistant.io/blog/2024/07/03/release-20247/#backward-incompatible-changes).

If your ZWaveJS server is up to date, look at [their troubleshooting page](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/connectivity-issues?id=problems-communicating-with-nodes).  In particular, look in the ZWaveJS logs for indications of trouble communicating with the keypads.

**Comment by wardrp** [comment]
Thanks for your reply. It is good to know you have not seen any issues with the keypads with HA core 2024.7.x.

I double checked and I am currently running versions of ZWaveJS server (v1.36.0) and ZWave Addon (v0.6.2) which are OK for the HA Core 2024.7.x update, according to the release notes. 

When checking the ZWave Addon version I did find that the option to Auto Start with HA had become disabled somehow. I am pretty sure I enabled it when I first set it up, but maybe when I switched my HA VM to a new host it got disabled. I just created new VM and restored my backup. Everything seemed to work fine so I didn't go looking at every option setting. Anyway not sure this affected anything since my ZWave devices always worked after a VM reboot. I also noticed that the option to Auto Update was Enabled which I am not sure is a good idea or not considering how fragile the ZWave network and devices seem to be. So I am not sure when it got updated, maybe that was the issue and I only noticed it when I rebooted the VM after the HA Core 2024.7.x update. That may also explain why the issue was still there after I restored back to 2024.6.4. 

When I was having the issue with the keypads, I checked the HA logs, but forgot about the ZWave logs. Thanks for that reminder. 
Checking the ZWave addon logs now (with everything working) I only see some repeating messages about a failed commands to a couple ZCombo-G smoke alarms and the Garage Door opener. Nothing for the Ring Keypads.
Under ZWave Server Logs I don't see much of anything. Only that I am "subscribed to ZWave JS log messages..." But the log level is set to "Info" which I though would include Warnings and Errors. Should I change the log level to "Warn" or "Error"?

Anyway if I get brave enough to try the HA Core 2024.7.x update again I will check these logs. The reason I am so afraid of it is because the process of deleting and re-adding the Keypads is very difficult. I have to bring them near the HomeAssistant PC and also have to extract one of the power supplies from the wall. The whole process took me half a day last time.

By the way, sorry for posting this on your GitHub Issues, but I wasn't sure how I could send you a PM directly.

**Comment by ImSorryButWho** [comment]
Hang on - are you running both the ZWaveJS Addon _and_ a separate instance of the ZWaveJS Server?  The ZWaveJS Addon includes the server.  You definitely don't want to be running two instances of the server -- only one can actually use your ZWave stick at a time.

If that's what's going on, a conflict between them (probably involving encryption keys) could definitely cause your problem.  If one that thinks the S2 keys are different grabbed control of the stick, the network would be up, but encrypted messages couldn't get through.  If things are working now, with the Addon in control, then uninstall the bare server.

Unrelatedly, the keypad will work happily with any random USB charger with a microusb cable.  There's no need to dig anything out of the wall.

**Comment by wardrp** [comment]
I don't think so. I am using the ZWaveJS Addon and the ZWave integration which I believe is what gives me the server. When I look at ZWave integration and then under my hub I go to configure it shows a driver and server version. It shows all 10 of my Zwave devices being connected. As far as I understand when I was first setting this up I first had to install the Zwave Addon which then allowed me to use the ZWave integration which actually provided the "server". But I could be totally confused and maybe didn't need to install the addon at all?

**Comment by ImSorryButWho** [comment]
Okay, just a terminology misunderstanding.  ZwaveJS server is the program that actually talks to your Zwave stick and controls your network.  You need exactly one copy of this running.  The easiest way to get it running is inside the ZwaveJS Add-On.

The server talks to the ZwaveJS integration inside home assistant, which exposes the devices to the big HA system. 

My concern was that you were running a separate copy of the server outside the Add-On, and one inside.  But it doesn't sound like that's the situation.
