### ISSUE TITLE
Keypad gen 1

### ISSUE THREAD

**Issue by sleevezipper** [ImSorryButWho/HomeAssistantNotes#4]
Hi! 

Thanks for the great writeup! 

I bought a keypad gen 1 and am using your blueprint to disarm the alarm and it works great! I'm now trying to use the Indicator command class and I can't get it to work. I'm guessing I need some different values for Property, Endpoint and PropertyKey. How did you find out the values for the gen 2?

**Comment by ImSorryButWho** [comment]
The indicator command class, version 4, includes the ability for devices that support indicators to report a description of what indicators they support.  When ZWave JS does an interview, it pulls those, and makes them available in the ZWaveJS2MQTT interface.  Note that at least for the v2 keypad, a bunch of the indicators that it claims to support don't actually do anything, but in playing with the control panel it was pretty simple to figure out which ones actually work.

If there's no descriptions that show up, the v1 keypad presumably doesn't support descriptions.  That's kind of a pain.  The good news is that indicator IDs are limited to a range of 0-255, and Ring seems to have stuck to the low end of that range for at least the v2 keypad.  I'd just walk through the whole range, try to turn each one on, and see what (if anything) happens.  Not fun, but it shouldn't take more than an hour or two of experimentation.

**Comment by ImSorryButWho** [comment]
Actually, one other point: taking a closer look at the Z-Wave docs, there's a set of standard indicators that were used in earlier versions.  Take a look at https://www.silabs.com/documents/public/miscellaneous/SDS14220-Indicator-Command-Class.xlsx as a starting point.

**Comment by sleevezipper** [comment]
Thanks for your reply! I believe I am running into a limitation of the built in zwave js implementation as [this issue](https://github.com/zwave-js/node-zwave-js/issues/6) states that the Indicator command class isn't fully implemented yet. I'll migrate to ZWaveJS2MQTT and see if it gives me more options. If I get this to work I'll submit a PR so you can include instructions and a blueprint for v1 as well.

**Comment by sleevezipper** [comment]
Added docs for keypad v1 in #5 . Thanks for your help!
